name: Daily Recommender For Problem Solving

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Activate Virtual Environment
      run: |
        source bin/activate
        pip install bs4
    - name: Run Script
      run: |
        python3 ./src/recommender.py
